#! /bin/bash

YEAR=2022

# Warn and quit if no .cookie file found
COOKIE=.cookie
if [ ! -f "$COOKIE" ]; then
	echo "Store your AoC session cookie in '.cookie'!"
	exit 0
fi

# Identify the day after the last day's input fetched
RESOURCES=src/main/resources
LAST_DAY=$(fd -I 'day\d{2}\.txt' $RESOURCES | tail -n 1 | rg -o --pcre2 '(?<=day)\d{2}')

if [ -z "$LAST_DAY" ]; then
	CURRENT_DAY=1
else
	CURRENT_DAY=$(($LAST_DAY + 1))
fi

# Don't try to fetch inputs after the 25th
if (($CURRENT_DAY > 25)); then
	echo "You've already got all the inputs for Year $YEAR!"
	exit 0
fi

PADDED=$(printf "%02d" $CURRENT_DAY)
INPUT_PATH="$RESOURCES"/day"$PADDED".txt

# Fetch the input with aoc-cli
aoc -s $COOKIE -y $YEAR -d $CURRENT_DAY -I -i $INPUT_PATH download
