#! /bin/bash

COOKIE=.cookie
if [ ! -f "$COOKIE" ]; then
	echo "Store your AoC session cookie in '.cookie'!"
	exit 0
fi

LAST_DAY=$(fd -I 'day\d{2}\.txt' src/main/resources | tail -n 1 | rg -o --pcre2 '(?<=day)\d{2}')

if [ -z "$LAST_DAY" ]; then
	CURRENT_DAY=1
else
	CURRENT_DAY=$(($LAST_DAY + 1))
fi

PADDED=$(printf "%02d" $CURRENT_DAY)

aoc -s .cookie -y 2022 -d $CURRENT_DAY -I -i src/main/resources/day"$PADDED".txt download
